// The planted storylines in the demo database, each phrased as the question a manager
// would actually ask. Numbers are what validation/planted_insights.sql reproduces.
export interface Insight {
  id: number; title: string; headline: string; module: string; question: string;
  persona: string;                  // subject best placed to ask it
  star?: boolean;
}

export const INSIGHTS: Insight[] = [
  { id: 15, star: true, module: "Regulatory", title: "HIE blind spot at SHJ01",
    headline: "Riayati SLA attainment fell to 36% in Q2 2026 with 300+ submissions stuck. Nobody noticed for a quarter.",
    question: "What share of encounters were submitted to the HIE within SLA, by branch and quarter?", persona: "demo.auditor" },
  { id: 16, star: true, module: "Claims", title: "Scrubber warnings that came true",
    headline: "Overridden authorisation findings were later denied for exactly that reason — AED 45k of claims.",
    question: "Which scrubber findings did we override that were later denied for exactly that reason?", persona: "demo.claims" },
  { id: 22, star: true, module: "Marketing", title: "Evening call abandonment",
    headline: "22% of inbound calls abandoned between 18:00 and 20:00, against 7% the rest of the day.",
    question: "What is our call abandonment rate by hour of day?", persona: "demo.owner" },
  { id: 2, module: "Claims", title: "The slow payer",
    headline: "Gulf Shield Insurance averages 130 days to remit; every other payer sits at 60–75.",
    question: "Which payer takes the longest to remit?", persona: "demo.claims" },
  { id: 4, module: "Operations", title: "Nurse-station bottleneck",
    headline: "DXB01 Monday and Tuesday evenings: median nurse-to-doctor wait 25 min vs 15 elsewhere. One nurse rostered.",
    question: "Where are patients waiting longest between nurse and doctor, by branch and weekday?", persona: "demo.owner" },
  { id: 10, module: "Cash", title: "Friday cash shortages",
    headline: "One SHJ01 cashier: 106 Friday sessions, AED 131 short on average. Every other cashier is near zero.",
    question: "Which cashier sessions had cash variances, by cashier and weekday?", persona: "demo.billing" },
  { id: 12, module: "Billing", title: "Credit-note outlier",
    headline: "One DXB01 dentist raised 12 price-correction credit notes in Q1 2026; peers raised one each.",
    question: "Why were credit notes issued in Q1 2026, and which doctor accounts for most of them?", persona: "demo.billing" },
  { id: 5, module: "Operations", title: "Ramadan afternoons",
    headline: "Afternoon no-shows rise to 15% during Ramadan against 10% outside it.",
    question: "How did Ramadan affect afternoon no-show rates compared with the rest of the year?", persona: "demo.manager" },
  { id: 18, module: "Front office", title: "Saturday queue abandonment",
    headline: "DXB01 Saturday evenings: 10% of tokens abandoned vs 4–6% everywhere else — it tracks queue length, not doctor delay.",
    question: "What is our token abandonment rate by branch and weekday in the evening?", persona: "demo.owner" },
  { id: 19, module: "Claims", title: "The eligibility gap",
    headline: "About 15% of insurance visits were billed with no eligibility check at all.",
    question: "How many insurance visits were billed without an eligibility check, by branch?", persona: "demo.claims" },
  { id: 20, module: "Claims", title: "Approved but never delivered",
    headline: "AED 400k+ of approved prior authorisations expired without a single unit consumed — a warm recall list.",
    question: "How many approved prior authorisations expired unused, and what were they worth?", persona: "demo.claims" },
  { id: 3, module: "Claims", title: "Unsubmitted backlog",
    headline: "170+ AUH01 claims not verified and older than 30 days — revenue at risk.",
    question: "How many claims are not submitted and older than 30 days, by branch and regulator?", persona: "demo.claims" },
  { id: 7, module: "Revenue", title: "January 2025 tariff uplift",
    headline: "The cash price list rose 6% on 1 January 2025; average cash invoice value stepped up with it.",
    question: "What did the January 2025 tariff change do to average cash invoice value, by quarter?", persona: "demo.owner" },
  { id: 8, module: "Cash", title: "BNPL is growing",
    headline: "Tabby and Tamara went from 16% of cash collections in 2024 to 23% in 2026.",
    question: "How much did we collect through Tabby and Tamara each year, as a share of cash collections?", persona: "demo.billing" },
  { id: 17, module: "Coding", title: "Coder-query drag",
    headline: "Invoices with an unanswered coder query deny at three times the base rate.",
    question: "Which doctors have the most open coder queries, and how much claim value is behind them?", persona: "demo.coder" },
  { id: 21, module: "Regulatory", title: "TATMEEN reporting gap",
    headline: "8–9% of serialised drug events are reported to TATMEEN late or never.",
    question: "What share of serialised drug dispenses were reported to TATMEEN on time, by branch?", persona: "demo.auditor" },
  { id: 6, module: "Marketing", title: "Campaign quality",
    headline: "Instagram brings the most leads at the worst conversion; Google Ads and referrals the reverse.",
    question: "Which campaigns gave the best and worst cost per converted patient?", persona: "demo.owner" },
  { id: 14, module: "Dental", title: "Treatment plan gap",
    headline: "Around AED 3M of accepted dental treatment has no appointment booked.",
    question: "How much accepted dental treatment is unscheduled, by branch?", persona: "demo.owner" },
  { id: 9, module: "Stock", title: "Expiry risk",
    headline: "Batches at or near expiry with the cost value at risk, by branch.",
    question: "Which stock batches expire in the next 30 days and what is the value at risk?", persona: "demo.owner" },
  { id: 24, module: "Finance", title: "Marketing over budget",
    headline: "DXB01 marketing ran AED 406k against a AED 300k plan in 2026 while delivering fewer converted patients.",
    question: "How is marketing spend tracking against budget by branch this year?", persona: "demo.owner" },
  { id: 11, module: "Lab", title: "Outsourced lab delay",
    headline: "Vitamin D turnaround from the external lab doubled from November 2025.",
    question: "How did lab turnaround for outsourced tests change from November 2025?", persona: "demo.owner" },
  { id: 23, module: "Controls", title: "Discount-limit breaches",
    headline: "Discounts approved above the approver's authorised percentage, clustered on two users.",
    question: "Which invoices had discounts exceeding the approver's authorised limit, and who approved them?", persona: "demo.billing" },
  { id: 1, module: "Claims", title: "Prior-auth leakage",
    headline: "One Dubai dentist carries three times the group's authorisation-family denials from mid-2025.",
    question: "Which dentist has the highest authorization-related denials, and since when?", persona: "demo.claims" },
  { id: 13, module: "Operations", title: "Summer dip and school spike",
    headline: "July–August volume drops ~26%; paediatrics spikes late August into September.",
    question: "How did monthly visit volume change across the year, and which departments drove the September spike?", persona: "demo.owner" },
];
